#!/usr/bin/env bash

# Inspired by:
# https://github.com/mathiasbynens/dotfiles/blob/main/.macos
# https://github.com/searls/icloud-dotfiles/blob/master/bin/setup-new-mac

set -e

## Disabling shadows on windows when taking screenshots - requires killall SystemUIServer
defaults write com.apple.screencapture disable-shadow -bool true

## allow disabling inline video in safari http://www.kirkville.com/stop-auto-play-videos-from-annoying-you-in-your-browser/
defaults write com.apple.Safari WebKitMediaPlaybackAllowsInline -bool false
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2AllowsInlineMediaPlayback -bool false

# Finder: show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Disable the warning when changing a file extension
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# Avoid creating .DS_Store files on network or USB volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

# Use list view in all Finder windows by default
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

# Show the ~/Library folder
chflags nohidden ~/Library

# Disable auto-correct
defaults write com.apple.Safari WebAutomaticSpellingCorrectionEnabled -bool false

# Disable auto-correct
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

# Require password immediately after sleep or screen saver begins
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0

###############################################################################
# Google Chrome & Google Chrome Canary                                        #
###############################################################################

# Use the system-native print preview dialog
defaults write com.google.Chrome DisablePrintPreview -bool true
defaults write com.google.Chrome.canary DisablePrintPreview -bool true

# Expand the print dialog by default
defaults write com.google.Chrome PMPrintingExpandedStateForPrint2 -bool true
defaults write com.google.Chrome.canary PMPrintingExpandedStateForPrint2 -bool true

defaults write com.apple.Safari ShowOverlayStatusBar -bool true

defaults write com.apple.menuextra.battery ShowPercent -string "YES"

defaults write com.apple.sound.beep.feedback -int 1

# Always display Volume menubar item
PLISTBUDDY=/usr/libexec/plistbuddy
FILE=~/Library/Preferences/com.apple.systemuiserver.plist
$PLISTBUDDY -c "add :menuExtras:0 string '/System/Library/CoreServices/Menu Extras/Volume.menu'" $FILE

# Make Safari’s search banners default to Contains instead of Starts With
defaults write com.apple.Safari FindOnPageMatchesWordStartsOnly -bool false

# Do not preload Top Hits in the background
defaults write com.apple.Safari PreloadTopHit -bool false

# Display -> Automatically adjust brightness
# doesn't work, add to manual list of steps
# defaults write /Library/Preferences/com.apple.iokit.AmbientLightSensor "Automatic Display Enabled" -bool false

defaults write com.apple.Safari FindOnPageMatchesWordStartsOnly -bool FALSE

# safari transparency
defaults write com.apple.universalaccess reduceTransparency -bool true

# not yet sure if worked
defaults write com.apple.Safari CanPromptForPushNotifications -bool false

defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false
defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

# QuickLook plugin to view files without their own dedicated plugin, e.g. README
# Note: Need to relaunch Finder for this to take effect
xattr -cr ~/Library/QuickLook/QLStephen.qlgenerator
qlmanage -r
qlmanage -r cache

# Fix VSCode key repeat for NeoVim
defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false

# Additions by andyw8
# doesn't work?
defaults write com.apple.Safari ShowStatusBar -boolean true

defaults write com.apple.menuextra.battery ShowPercent -string "YES"

defaults write com.apple.sound.beep.feedback -int 1

# Always display Volume menubar item
PLISTBUDDY=/usr/libexec/plistbuddy
FILE=~/Library/Preferences/com.apple.systemuiserver.plist
$PLISTBUDDY -c "add :menuExtras:0 string '/System/Library/CoreServices/Menu Extras/Volume.menu'" $FILE

# Make Safari’s search banners default to Contains instead of Starts With
defaults write com.apple.Safari FindOnPageMatchesWordStartsOnly -bool false

# Do not preload Top Hits in the background
defaults write com.apple.Safari PreloadTopHit -bool false

# Display -> Automatically adjust brightness
# doesn't work, add to manual list of steps
# defaults write /Library/Preferences/com.apple.iokit.AmbientLightSensor "Automatic Display Enabled" -bool false

defaults write com.apple.Safari FindOnPageMatchesWordStartsOnly -bool FALSE

# safari transparency
# System Preferences > Accesibility > Display > Reduce Transparency.
